def bradesco_portabilidade():
    return """
    CREATE 
      (`0` :Node ) ,
      (`1` :Node ) ,
      (`2` :CONTRATO_FORNECEDOR {`"NAME"`:"<CONTRATO_FORNECEDOR>",`"ID"`:"<CONTRATO_FORNECEDOR>"}) ,
      (`3` :REGRA {`"ID"`:"BRADESCO_<CONTRATO_FORNECEDOR>_POTABILIDADE_VIGENCIA_0",`"NAME"`:"VIGENCIA"}) ,
      (`4` :REGRA_RESPOSTA {`"ID"`:"BRADESCO_<CONTRATO_FORNECEDOR>_PORTABILIDADE_NAO_ACEITO_0",`"NAME"`:"NÃO ACEITO",`"INFO"`:"",`"MSG"`:"Vigência inválida"}) ,
      (`5` :REGRA {`"ID"`:"BRADESCO_<CONTRATO_FORNECEDOR>_POTABILIDADE_TIPO_PORTABILIDADE_0",`"NAME"`:"TIPO PORTABILIDADE"}) ,
      (`6` :REGRA_RESPOSTA {`"ID"`:"BRADESCO_<CONTRATO_FORNECEDOR>_PORTABILIDADE_ACEITO_4",`"NAME"`:"ACEITO",`"INFO"`:"<INFO_EXTRAJUDICIAL>",`"MSG"`:""}) ,
      (`7` :REGRA {`"ID"`:"BRADESCO_<CONTRATO_FORNECEDOR>_POTABILIDADE_STATUS_PLANO_ANTERIOR_0",`"NAME"`:"STATUS PLANO ANTERIOR"}) ,
      (`8` :REGRA {`"ID"`:"BRADESCO_<CONTRATO_FORNECEDOR>_POTABILIDADE_PERIODO_PORTABILIDADE_0",`"NAME"`:"PERIODO PORTABILIDADE"}) ,
      (`9` :REGRA {`"ID"`:"BRADESCO_<CONTRATO_FORNECEDOR>_POTABILIDADE_CPT_0",`"NAME"`:"CPT"}) ,
      (`10` :REGRA_RESPOSTA {ID:"BRADESCO_<CONTRATO_FORNECEDOR>_PORTABILIDADE_NAO_ACEITO_1",NAME:"NÃO ACEITO",INFO:"",MSG:"Plano inativo"}) ,
      (`11` :REGRA_RESPOSTA {ID:"BRADESCO_<CONTRATO_FORNECEDOR>_PORTABILIDADE_NAO_ACEITO_2",NAME:"NÃO ACEITO",INFO:"",MSG:"Período de portabilidade maior que 4 meses"}) ,
      (`12` :REGRA {`"ID"`:"BRADESCO_<CONTRATO_FORNECEDOR>_POTABILIDADE_PRIMEIRA_PORTABILIDADE_1",`"NAME"`:"PRIMEIRA_PORTABILIDADE"}) ,
      (`13` :REGRA {`"ID"`:"BRADESCO_<CONTRATO_FORNECEDOR>_POTABILIDADE_PRIMEIRA_PORTABILIDADE_0",`"NAME"`:"PRIMEIRA_PORTABILIDADE"}) ,
      (`14` :REGRA {`"ID"`:"BRADESCO_<CONTRATO_FORNECEDOR>_POTABILIDADE_TEMPO_PLANO_1",`"NAME"`:"TEMPO PLANO"}) ,
      (`15` :REGRA {`"ID"`:"BRADESCO_<CONTRATO_FORNECEDOR>_POTABILIDADE_TEMPO_PLANO_0",`"NAME"`:"TEMPO PLANO"}) ,
      (`16` :REGRA {`"ID"`:"BRADESCO_<CONTRATO_FORNECEDOR>_POTABILIDADE_ADIMPLENTE_0",`"NAME"`:"ADIMPLENTE"}) ,
      (`17` :REGRA_RESPOSTA {ID:"BRADESCO_<CONTRATO_FORNECEDOR>_PORTABILIDADE_NAO_ACEITO_3",NAME:"NÃO ACEITO",INFO:"",MSG:"Tempo de plano menor que 36 meses"}) ,
      (`18` :REGRA_RESPOSTA {ID:"BRADESCO_<CONTRATO_FORNECEDOR>_PORTABILIDADE_ACEITO_0",NAME:"ACEITO",INFO:"Seguintes documentos à operadora do plano de destino:,`- Carta da operadora anterior, em papel timbrado, com registro da operadora, com carimbo, local, data e assinatura, contendo meu nome completo, o tempo de permanência no último plano de origem, bem como a data de minha inclusão, indicação de que houve ou não o cumprimento de CPT, tipo de contratação e informações sobre o tipo de plano`:'nome do plano, número de registro na ANS, acomodação, segmentação assistencial e preço; ou',MSG:""}) ,
      (`19` :REGRA_RESPOSTA {ID:"BRADESCO_<CONTRATO_FORNECEDOR>_PORTABILIDADE_NAO_ACEITO_4",NAME:"NÃO ACEITO",INFO:"",MSG:"Beneficiário inadimplente"}) ,
      (`20` :REGRA {`"ID"`:"BRADESCO_<CONTRATO_FORNECEDOR>_POTABILIDADE_ADIMPLENTE_1",`"NAME"`:"ADIMPLENTE"}) ,
      (`21` :REGRA_RESPOSTA {ID:"BRADESCO_<CONTRATO_FORNECEDOR>_PORTABILIDADE_ACEITO_1",NAME:"ACEITO",INFO:"Seguintes documentos à operadora do plano de destino:,`- Carta da operadora anterior, em papel timbrado, com registro da operadora, com carimbo, local, data e assinatura, contendo meu nome completo, o tempo de permanência no último plano de origem, bem como a data de minha inclusão, indicação de que houve ou não o cumprimento de CPT, tipo de contratação e informações sobre o tipo de plano`:'nome do plano, número de registro na ANS, acomodação, segmentação assistencial e preço; ou',MSG:""}) ,
      (`22` :REGRA_RESPOSTA {ID:"BRADESCO_<CONTRATO_FORNECEDOR>_PORTABILIDADE_NAO_ACEITO_6",NAME:"NÃO ACEITO",INFO:"",MSG:"Beneficiário inadimplente"}) ,
      (`24` :REGRA_RESPOSTA {ID:"BRADESCO_<CONTRATO_FORNECEDOR>_PORTABILIDADE_NAO_ACEITO_5",NAME:"NÃO ACEITO",INFO:"",MSG:"Tempo de plano menor que 36 meses"}) ,
      (`25` :REGRA {`"ID"`:"BRADESCO_<CONTRATO_FORNECEDOR>_POTABILIDADE_TEMPO_PLANO_2",`"NAME"`:"TEMPO PLANO"}) ,
      (`26` :REGRA {`"ID"`:"BRADESCO_<CONTRATO_FORNECEDOR>_POTABILIDADE_TEMPO_PLANO_3",`"NAME"`:"TEMPO PLANO"}) ,
      (`27` :REGRA {`"ID"`:"BRADESCO_<CONTRATO_FORNECEDOR>_POTABILIDADE_ADIMPLENTE_2",`"NAME"`:"ADIMPLENTE"}) ,
      (`28` :REGRA_RESPOSTA {ID:"BRADESCO_<CONTRATO_FORNECEDOR>_PORTABILIDADE_NAO_ACEITO_7",NAME:"NÃO ACEITO",INFO:"",MSG:"Tempo de plano menor que 24 meses"}) ,
      (`29` :REGRA_RESPOSTA {ID:"BRADESCO_<CONTRATO_FORNECEDOR>_PORTABILIDADE_NAO_ACEITO_8",NAME:"NÃO ACEITO",INFO:"",MSG:"Beneficiário inadimplente"}) ,
      (`30` :REGRA_RESPOSTA {ID:"BRADESCO_<CONTRATO_FORNECEDOR>_PORTABILIDADE_ACEITO_2",NAME:"ACEITO",INFO:"Seguintes documentos à operadora do plano de destino:,`- Carta da operadora anterior, em papel timbrado, com registro da operadora, com carimbo, local, data e assinatura, contendo meu nome completo, o tempo de permanência no último plano de origem, bem como a data de minha inclusão, indicação de que houve ou não o cumprimento de CPT, tipo de contratação e informações sobre o tipo de plano`:'nome do plano, número de registro na ANS, acomodação, segmentação assistencial e preço; ou',MSG:""}) ,
      (`31` :REGRA {`"ID"`:"BRADESCO_<CONTRATO_FORNECEDOR>_POTABILIDADE_ADIMPLENTE_3",`"NAME"`:"ADIMPLENTE"}) ,
      (`32` :REGRA_RESPOSTA {ID:"BRADESCO_<CONTRATO_FORNECEDOR>_PORTABILIDADE_NAO_ACEITO_10",NAME:"NÃO ACEITO",INFO:"",MSG:"Beneficiário inadimplente"}) ,
      (`33` :REGRA_RESPOSTA {ID:"BRADESCO_<CONTRATO_FORNECEDOR>_PORTABILIDADE_ACEITO_3",NAME:"ACEITO",INFO:"Seguintes documentos à operadora do plano de destino:,`- Carta da operadora anterior, em papel timbrado, com registro da operadora, com carimbo, local, data e assinatura, contendo meu nome completo, o tempo de permanência no último plano de origem, bem como a data de minha inclusão, indicação de que houve ou não o cumprimento de CPT, tipo de contratação e informações sobre o tipo de plano`:'nome do plano, número de registro na ANS, acomodação, segmentação assistencial e preço; ou',MSG:""}) ,
      (`35` :REGRA_RESPOSTA {ID:"BRADESCO_<CONTRATO_FORNECEDOR>_PORTABILIDADE_NAO_ACEITO_9",NAME:"NÃO ACEITO",INFO:"",MSG:"Tempo de plano menor que 12 meses"}) ,
      (`36` :REGRA_RESPOSTA ) ,
      (`37` :REGRA_RESPOSTA ) ,
      (`38` :REGRA_RESPOSTA ) ,
      (`2`)-[:`PARAMETROS` ]->(`3`),
      (`3`)-[:`PARAMETROS` {`"OP"`:"OR",`"COND1"`:"LT",`"VALUE1"`:"2018-01-01",`"COND2"`:''GT",`"VALUE2"`:"2019-07-01",`"KEY"`:"VIGENCIA"}]->(`4`),
      (`3`)-[:`PARAMETROS` {`"OP"`:"AND",`"COND1"`:"GTE",`"VALUE1"`:"2018-01-01",`"COND2"`:''LTE",`"VALUE2"`:"2019-07-01",`"KEY"`:"VIGENCIA"}]->(`5`),
      (`5`)-[:`PARAMETROS` {`"OP"`:"AND",`"COND1"`:"EQ",`"VALUE1"`:"LIQUIDAÇÃO EXTRAJUDICIAL",`"COND2"`:''",`"VALUE2"`:"",`"KEY"`:"TIPO_PORTABILIDADE"}]->(`6`),
      (`5`)-[:`PARAMETROS` {`"OP"`:"AND",`"COND1"`:"EQ",`"VALUE1"`:"NORMAL",`"COND2"`:''",`"VALUE2"`:"",`"KEY"`:"TIPO_PORTABILIDADE"}]->(`7`),
      (`7`)-[:`PARAMETROS` {`"OP"`:"AND",`"COND1"`:"EQ",`"VALUE1"`:"ATIVO",`"COND2"`:''",`"VALUE2"`:"",`"KEY"`:"STATUS_PLANO_ANTERIOR"}]->(`8`),
      (`8`)-[:`PARAMETROS` {`"OP"`:"AND",`"COND1"`:"LTE",`"VALUE1"`:'120',`"COND2"`:''",`"VALUE2"`:"",`"KEY"`:"PERIODO_PORTABILIDADE"}]->(`9`),
      (`7`)-[:`PARAMETROS` {`"OP"`:"AND",`"COND1"`:"NOTIN",`"VALUE1"`:'["ATIVO"]',`"COND2"`:''",`"VALUE2"`:"",`"KEY"`:"STATUS_PLANO_ANTERIOR"}]->(`10`),
      (`8`)-[:`PARAMETROS` {`"OP"`:"AND",`"COND1"`:"GT",`"VALUE1"`:'120',`"COND2"`:''",`"VALUE2"`:"",`"KEY"`:"PERIODO_PORTABILIDADE"}]->(`11`),
      (`9`)-[:`PARAMETROS` {`"OP"`:"AND",`"COND1"`:"EQ",`"VALUE1"`:"SIM",`"COND2"`:''",`"VALUE2"`:"",`"KEY"`:"CPT"}]->(`12`),
      (`9`)-[:`PARAMETROS` {`"OP"`:"AND",`"COND1"`:"NOTIN",`"VALUE1"`:'["SIM"]',`"COND2"`:''",`"VALUE2"`:"",`"KEY"`:"CPT"}]->(`13`),
      (`13`)-[:`PARAMETROS` {`"OP"`:"AND",`"COND1"`:"NOTIN",`"VALUE1"`:'["SIM"]',`"COND2"`:''",`"VALUE2"`:"",`"KEY"`:"PRIMEIRA_PORTABILIDADE"}]->(`14`),
      (`13`)-[:`PARAMETROS` {`"OP"`:"AND",`"COND1"`:"EQ",`"VALUE1"`:"SIM",`"COND2"`:''",`"VALUE2"`:"",`"KEY"`:"PRIMEIRA_PORTABILIDADE"}]->(`15`),
      (`15`)-[:`PARAMETROS` {`"OP"`:"AND",`"COND1"`:"GTE",`"VALUE1"`:'36',`"COND2"`:''",`"VALUE2"`:"",`"KEY"`:"TEMPO_PLANO"}]->(`16`),
      (`15`)-[:`PARAMETROS` {`"OP"`:"AND",`"COND1"`:"LT",`"VALUE1"`:'36',`"COND2"`:''",`"VALUE2"`:"",`"KEY"`:"TEMPO_PLANO"}]->(`17`),
      (`16`)-[:`PARAMETROS` {`"OP"`:"AND",`"COND1"`:"EQ",`"VALUE1"`:"SIM",`"COND2"`:''",`"VALUE2"`:"",`"KEY"`:"ADIMPLENTE"}]->(`18`),
      (`16`)-[:`PARAMETROS` {`"OP"`:"AND",`"COND1"`:"EQ",`"VALUE1"`:'["SIM"]',`"COND2"`:''",`"VALUE2"`:"",`"KEY"`:"ADIMPLENTE"}]->(`19`),
      (`14`)-[:`PARAMETROS` {`"OP"`:"AND",`"COND1"`:"GTE",`"VALUE1"`:'12',`"COND2"`:''",`"VALUE2"`:"",`"KEY"`:"TEMPO_PLANO"}]->(`20`),
      (`20`)-[:`PARAMETROS` {`"OP"`:"AND",`"COND1"`:"EQ",`"VALUE1"`:"SIM",`"COND2"`:''",`"VALUE2"`:"",`"KEY"`:"ADIMPLENTE"}]->(`21`),
      (`20`)-[:`PARAMETROS` {`"OP"`:"AND",`"COND1"`:"EQ",`"VALUE1"`:'["SIM"]',`"COND2"`:''",`"VALUE2"`:"",`"KEY"`:"ADIMPLENTE"}]->(`22`),
      (`14`)-[:`PARAMETROS` {`"OP"`:"AND",`"COND1"`:"LT",`"VALUE1"`:'12',`"COND2"`:''",`"VALUE2"`:"",`"KEY"`:"TEMPO_PLANO"}]->(`24`),
      (`12`)-[:`PARAMETROS` {`"OP"`:"AND",`"COND1"`:"EQ",`"VALUE1"`:"SIM",`"COND2"`:''",`"VALUE2"`:"",`"KEY"`:"PRIMEIRA_PORTABILIDADE"}]->(`25`),
      (`12`)-[:`PARAMETROS` {`"OP"`:"AND",`"COND1"`:"NOTIN",`"VALUE1"`:'["SIM"]',`"COND2"`:''",`"VALUE2"`:"",`"KEY"`:"PRIMEIRA_PORTABILIDADE"}]->(`26`),
      (`25`)-[:`PARAMETROS` {`"OP"`:"AND",`"COND1"`:"GTE",`"VALUE1"`:'24',`"COND2"`:''",`"VALUE2"`:"",`"KEY"`:"TEMPO_PLANO"}]->(`27`),
      (`25`)-[:`PARAMETROS` {`"OP"`:"AND",`"COND1"`:"LT",`"VALUE1"`:'24',`"COND2"`:''",`"VALUE2"`:"",`"KEY"`:"TEMPO_PLANO"}]->(`28`),
      (`27`)-[:`PARAMETROS` {`"OP"`:"AND",`"COND1"`:"EQ",`"VALUE1"`:'["SIM"]',`"COND2"`:''",`"VALUE2"`:"",`"KEY"`:"ADIMPLENTE"}]->(`29`),
      (`27`)-[:`PARAMETROS` {`"OP"`:"AND",`"COND1"`:"EQ",`"VALUE1"`:"SIM",`"COND2"`:''",`"VALUE2"`:"",`"KEY"`:"ADIMPLENTE"}]->(`30`),
      (`26`)-[:`PARAMETROS` {`"OP"`:"AND",`"COND1"`:"GTE",`"VALUE1"`:'12',`"COND2"`:''",`"VALUE2"`:"",`"KEY"`:"TEMPO_PLANO"}]->(`31`),
      (`31`)-[:`PARAMETROS` {`"OP"`:"AND",`"COND1"`:"EQ",`"VALUE1"`:'["SIM"]',`"COND2"`:''",`"VALUE2"`:"",`"KEY"`:"ADIMPLENTE"}]->(`32`),
      (`31`)-[:`PARAMETROS` {`"OP"`:"AND",`"COND1"`:"EQ",`"VALUE1"`:"SIM",`"COND2"`:''",`"VALUE2"`:"",`"KEY"`:"ADIMPLENTE"}]->(`33`),
      (`26`)-[:`PARAMETROS` {`"OP"`:"AND",`"COND1"`:"LT",`"VALUE1"`:'12',`"COND2"`:''",`"VALUE2"`:"",`"KEY"`:"TEMPO_PLANO"}]->(`35`),
      (`5`)-[:`RELATED_TO` ]->(`36`),
      (`5`)-[:`RELATED_TO` ]->(`37`),
      (`5`)-[:`RELATED_TO` ]->(`38`)
    """